
version: "3.8"
services:

  example_web:
    image: nginx
    ports:
      - 81:80
  
  http_log:
    environment:
      TARGET_HOST: example_web
      LOG_MAX_BODY_LENGTH: 50
      LOG_FORMAT: >
        '$$status $$body_bytes_sent "$$request" '
        '<<<< ((($$request_headers))) $$request_body '
        '>>>> ((($$resp_header))) $$resp_body'
    build:
      context: .
    ports:
      - 80:80