
version: "3.8"
services:

  example_web:
    image: traefik/whoami
    ports:
      - 81:80
  
  http_log:
    environment:
      TARGET_HOST: example_web
      LOG_FORMAT: >
        '$$status $$body_bytes_sent "$$request" '
        ''
        '<<<< ((($$request_headers))) $$request_body >>>>((($$resp_header))) $$lua_resp_body'
    build:
      context: .
    ports:
      - 80:80