
version: "3.8"
services:

  example_web:
    image: nginx:1.19
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    ports:
      - 81:80
  
  http_log:
    # image: bjuergens/http_log_proxy
    build:
      context: .
    environment:
      TARGET_HOST: example_web
      LOG_MAX_BODY_LENGTH: 50
      LOG_FORMAT: >
        '$$status $$body_bytes_sent "$$request" '
        '<<<< $$requ_headers ++++ $$request_body '
        '>>>> $$resp_headers_short ++++ $$resp_body'
    ports:
      - 80:80