
version: "3.7"
services:

  example_web:
    image: traefik/whoami
    ports:
      - 81:80
  
  http_log:
    environment:
      LOG_FORMAT: >
        '$$status $$body_bytes_sent "$$request" '
        '<<<<$$request_body >>>>$$lua_resp_body'
    build:
      context: .
    ports:
      - 80:80